version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - crm

  postgresql:
    image: postgres:11-alpine
    networks:
      - crm

  communication-api-test:
    image: crmnow/communication-api-test:latest
    build:
      context: .
      dockerfile: src/Communication/CRM.Communication.Api/Dockerfile
      target: functionaltest
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - rabbitmq
    # volumes:
    #   - ${COMMON_TESTRESULTSDIRECTORY:-/tmp}:${COMMON_TESTRESULTSDIRECTORY:-/tmp}
    volumes:
      - azp-data:/azp

  contact-api-test:
    image: crmnow/contact-api-test:latest
    build:
      context: .
      dockerfile: src/Contact/CRM.Contact.Api/Dockerfile
      target: functionaltest
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    networks:
      - crm
    depends_on:
      - rabbitmq
      - postgresql
    # volumes:
    #   - ${COMMON_TESTRESULTSDIRECTORY:-/tmp}:${COMMON_TESTRESULTSDIRECTORY:-/tmp}
    volumes:
      - azp-data:/azp


volumes:
  azp-data:
    name: azp-data
    external: true

networks:
  crm:
    name: crm-network-test
